name: wechat_assets_picker
version: 9.0.0-dev.2
description: |
  An image picker (also with videos and audio)
  for Flutter projects based on WeChat's UI,
  with full support for customization.
topics:
  - picker
  - image
  - audio
  - video
  - wechat

repository: https://github.com/fluttercandies/flutter_wechat_assets_picker
issue_tracker: https://github.com/fluttercandies/flutter_wechat_assets_picker/issues

environment:
  sdk: ^3.2.0
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter

  extended_image: ^8.1.0
  photo_manager: ^3.0.0-dev.1
  photo_manager_image_provider: ^2.0.0
  provider: ^6.0.5
  video_player: ^2.7.0
  flutter_stripe: ^10.0.0

dev_dependencies:
  flutter_lints: any
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
