name: socialmediaapp
description: "Welcome to WeShot, the ultimate social media haven where your moments aren't just shared, they're celebrated. Inspired by the visual storytelling of Pinterest, the vibrant community of Instagram, and the personalized experience of Spotify, WeShot is where life's snapshots become part of a larger, more colorful tapestry."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: '>=3.13.0'

dependencies:
  device_preview: ^1.1.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.5.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_redux: ^0.10.0
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  http: ^1.1.2
  image_picker: ^1.0.5
  logger: ^2.0.2+1
  redux: ^5.0.0
  redux_epics: ^0.15.1
  rxdart: ^0.27.7
  url_launcher: ^6.2.2
  path_provider: ^2.0.15
  image_picker_for_web: ^3.0.1
  cached_network_image: ^3.3.0
  change_app_package_name: ^1.1.0
  wechat_assets_picker:
  wechat_camera_picker: ^4.0.0
  extended_image: ^8.1.0
  package_info_plus: ^4.0.0
  path: ^1.8.0
  provider: ^6.0.2
  pdf: ^3.10.7
  intl: ^0.18.1
  fluttertoast: ^8.2.4
  firebase_auth: ^4.15.3
  google_sign_in: ^6.2.1
  flutter_stripe: ^10.0.0
  webview_flutter: ^4.4.2
  flutter_stripe_web: ^5.0.0
  get: ^4.6.6
  connectivity_plus: ^5.0.2
  pull_to_refresh_flutter3: ^2.0.2
  mockito: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  integration_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/
