// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9kxFsPr_Ld7YHCG7DESoddljI-JghHzc',
    appId: '1:688211195026:web:da6065f17877756869e24b',
    messagingSenderId: '688211195026',
    projectId: 'socialmedia-flutter-app',
    authDomain: 'socialmedia-flutter-app.firebaseapp.com',
    storageBucket: 'socialmedia-flutter-app.appspot.com',
    measurementId: 'G-G7B2JYMES2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMLY6TivgAzKzZxnq-ixZOtbA8CPr23ro',
    appId: '1:688211195026:ios:7b12c590f845cb7f69e24b',
    messagingSenderId: '688211195026',
    projectId: 'socialmedia-flutter-app',
    storageBucket: 'socialmedia-flutter-app.appspot.com',
    iosBundleId: 'com.example.socialmediaapp.RunnerTests',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9kxFsPr_Ld7YHCG7DESoddljI-JghHzc',
    appId: '1:688211195026:ios:608435ee1045f0cb69e24b',
    messagingSenderId: '688211195026',
    projectId: 'socialmedia-flutter-app',
    storageBucket: 'socialmedia-flutter-app.appspot.com',
    iosBundleId: 'com.example.socialmediaapp',
  );
}
